language: node_js
node_js:
  - 14
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - .next/cache
script:
  - yarn build
  - yarn next export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  fqdn: lifehack.nuscomputing.com
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
